import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/layout";
import Footer from "./Footer/layout";
import { Playfair_Display } from 'next/font/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alchemist",
  description: "Generated by create next app",
  icons: {
            icon: '/favicon.ico', // Path to your favicon.jpg
          },
};

import { Space_Grotesk, Inter } from 'next/font/google';

const space = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
});

const inter = Inter({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className} font-body`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
